server.port=8084

spring.application.name=gateway-service

spring.cloud.gateway.server.webmvc.routes[0].id=documents
spring.cloud.gateway.server.webmvc.routes[0].uri=http://documents:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/documents/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/api/(?<segment>.*), /${segment}

spring.cloud.gateway.server.webmvc.routes[1].id=comments
spring.cloud.gateway.server.webmvc.routes[1].uri=http://comments:8083
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/comments/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/api/(?<segment>.*), /${segment}

spring.cloud.gateway.server.webmvc.routes[2].id=auth
spring.cloud.gateway.server.webmvc.routes[2].uri=http://auth:8085
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=RewritePath=/api/(?<segment>.*), /${segment}